version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  # SONARCLOUD
  node-sonarcloud:
    docker:
      - image: cimg/node:18.18.1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - sonarcloud/scan

  # SONARQUBE
  sonarqube:
    working_directory: ~/build
    docker:
      - image: sonarsource/sonar-scanner-cli
    resource_class: small
    steps:
     - run: sudo apt-get update
    - run: sudo apt-get upgrade -y
    - run: sudo apt-get install -y git curl openssh-client

      - run: find .
      - attach_workspace:
          at: ~/workspace
      - run: |
          # Set branch
          SONAR_BRANCH="${CIRCLE_BRANCH:-master}"
          echo "Running SonarQube analysis on branch: $SONAR_BRANCH"

          sonar-scanner \
            -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
            -Dsonar.host.url="http://localhost:9000" \
            -Dsonar.login="$SONAR_TOKEN" \
            -Dsonar.branch.name="$SONAR_BRANCH" \
            -Dsonar.sources="customer-portal/src,api-server" \
            -Dsonar.exclusions="**/node_modules/**,**/build/**"

workflows:
  main:
    jobs:
      - say-hello
      - node-sonarcloud:
          context: SonarCloud
      - sonarqube
