version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  # -----------------------
  # SONARCLOUD 
  node-sonarcloud:
    docker:
      - image: cimg/node:18.18.1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - sonarcloud/scan  

  # -----------------------
  # SONARQUBE 
   sonarqube:
    working_directory: ~/build
    docker:
      - image: cimg/node:18.18.1
    resource_class: small
    steps:
      - checkout
      - run:
          name: Install SonarQube Scanner
          command: |
            npm install -g sonarqube-scanner
      - run:
          name: Show files
          command: find .
      - run:
          name: Run SonarQube scan
          command: |
            SONAR_BRANCH="${CIRCLE_BRANCH:-master}"
            echo "Running SonarQube analysis on branch: $SONAR_BRANCH"
            sonar-scanner \
              -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
              -Dsonar.host.url="$SONAR_HOST_URL" \
              -Dsonar.login="$SONAR_TOKEN" \
              -Dsonar.branch.name="$SONAR_BRANCH" \
              -Dsonar.sources="customer-portal/src,api-server" \
              -Dsonar.exclusions="**/node_modules/**,**/build/**"

workflows:
  main:
    jobs:
      - say-hello
      - node-sonarcloud:
          context: SonarCloud
      - sonarqube
