version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  # SONARCLOUD
  node-sonarcloud:
    docker:
      - image: cimg/node:18.18.1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - sonarcloud/scan

  # SONARQUBE
 sonarqube:
  working_directory: ~/build
  docker:
    - image: sonarsource/sonar-scanner-cli
  resource_class: small
  steps:
    - checkout
    - run: find .
    - run: |
        SONAR_BRANCH="${CIRCLE_BRANCH:-master}"
        sonar-scanner \
          -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
          -Dsonar.host.url="http://localhost:9000" \
          -Dsonar.login="$SONAR_TOKEN" \
          -Dsonar.branch.name="$SONAR_BRANCH" \
          -Dsonar.sources="customer-portal/src,api-server" \
          -Dsonar.exclusions="**/node_modules/**,**/build/**"


workflows:
  main:
    jobs:
      - say-hello
      - node-sonarcloud:
          context: SonarCloud
      - sonarqube
